version: '3'
services:
  myla-backend:
    image: myla-backend
    hostname: myla-backend
    build:
      context: ./backend
    networks:
      - myla
    depends_on:
      - postgres
    command: sh -c "dockerize -wait tcp://postgres:5432 -timeout 300s -wait-retry-interval 5s node index.js"

  postgres:
    image: postgres:12
    hostname: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${postgres_password}
      POSTGRES_USER: ${postgres_user}
    networks:
      - myla
    volumes:
      - ./database/:/docker-entrypoint-initdb.d/

  pgadmin:
    image: dpage/pgadmin4:4.16
    hostname: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${pgadmin_user} 
      PGADMIN_DEFAULT_PASSWORD: ${pgadmin_password}
    networks:
      - myla
    depends_on:
      - postgres
    ports:
      - 8080:80
    logging:
      driver: none
  
  nginx: 
    image: my-nginx
    hostname: nginx
    build: 
      context: ./nginx
    volumes:
      - ./nginx/nginx-frontend.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    networks:
     - myla
    depends_on: 
      - postgres
      - myla-backend
    restart: always

networks:
  myla: