version: '3'
services:
  myla-frontend:
    image: myla-frontend
    hostname: myla-frontend
    build:
      context: ./frontend
    networks:
      - myla
    depends_on:
      - postgres
      - myla-backend

  myla-backend:
    image: myla-backend
    hostname: myla-backend
    build:
      context: ./backend
    networks:
      - myla
    depends_on:
      - postgres

  postgres:
    image: postgres:12
    hostname: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${postgres_password}
      POSTGRES_USER: ${postgres_user}
    networks:
      - myla
    volumes:
      - ./database/:/docker-entrypoint-initdb.d/

  pgadmin:
    image: dpage/pgadmin4:4.16
    hostname: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${pgadmin_user} 
      PGADMIN_DEFAULT_PASSWORD: ${pgadmin_password}
    networks:
      - myla
    depends_on:
      - postgres
    ports:
      - 8080:80
    logging:
      driver: none
  
  nginx: 
    image: nginx:latest
    hostname: nginx
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    networks:
     - myla
    depends_on: 
      - postgres
      - myla-frontend
      - myla-backend

networks:
  myla: